airbnb_listings:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: mvaler
      password: mypostgres
      port: 5432
      dbname: airbnb
      schema: raw
      threads: 4